[project]
name = "testpmdrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "albumentations>=2.0.8",
    "evaluate>=0.4.6",
    "jiwer>=4.0.0",
    "keras>=3.14.1",
    "matplotlib>=3.10.9",
    "opencv-python>=4.13.0.92",
    "pillow>=12.2.0",
    "tensorflow>=2.21.0",
    "tqdm>=4.67.3",
    "transformers>=5.12.1",
    "wandb>=0.27.2",
]
